// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcishiiqpxeeoqoxzfvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjaXNoaWlxcHhlZW9xb3h6ZnZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTQzMjcsImV4cCI6MjA2Mzk5MDMyN30.TmOjbJF70B8Po51pYNFS7eY73L_KMFrCb63dkmfijxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);